import streamlit as st
from streamlit_agraph import agraph, Node, Edge, Config
from retail_agent import analyze_event_impact

# Set up the page layout
st.set_page_config(page_title="Event-Driven Impact Visualizer", layout="wide")

st.title("Event-Driven Market Impact Visualizer 🕸️")
st.markdown("Analyze macroeconomic events and news to visualize the ripple effects on various industries based on extracted investment logic.")

# --- 1. User Input Section ---
st.header("1. Input Market Context")
input_type = st.radio("Select Input Mode:", ["Text Description", "News Article URL"])

if input_type == "Text Description":
    user_input = st.text_area(
        "Describe the event:", 
        "Malaysia announces a complete ban on vapes starting next month."
    )
else:
    user_input = st.text_input(
        "Paste URL (or headline):", 
        "https://www.thestar.com.my/news/nation/vape-ban"
    )

analyze_button = st.button("Synthesize Impact Graph", type="primary")

st.divider()

# --- 2. Dynamic Network Graph Section ---
if analyze_button and user_input.strip():
    st.header("2. Impact Visualization (Retail Logic)")
    
    with st.spinner("Retrieving logic rules from Vector DB and synthesizing impact..."):
        
        # CALL YOUR BACKEND LOGIC HERE
        graph_data = analyze_event_impact(user_input)
        
        nodes = []
        edges = []

        event_name = graph_data.get("event_name", "Trigger Event")
        sector_nodes = graph_data.get("nodes", [])
        retrieved_sources = graph_data.get("sources_retrieved", [])

        # Central Node (The Trigger Event)
        nodes.append(Node(
            id="Event", 
            label=f"Event:\n{event_name}", 
            size=35, 
            shape="diamond",
            color="#2B7CE9", # Blue
            title="The macroeconomic or regulatory trigger."
        ))

        # Loop through the dynamic nodes generated by Gemini
        for sector in sector_nodes:
            node_id = sector.get("id", "Unknown Sector")
            impact = sector.get("impact", "POSITIVE").upper()
            reasoning = sector.get("reasoning", "No reasoning provided.")
            
            # Color code based on impact
            node_color = "#00CC96" if "POSITIVE" in impact else "#FF4B4B"
            
            # Create the node
            nodes.append(Node(
                id=node_id, 
                label=node_id, 
                size=25, 
                color=node_color,
                title=f"{impact}: {reasoning}" # Hover text
            ))
            
            # Create the connection
            edges.append(Edge(source="Event", target=node_id, label=impact))

        # Graph Configuration
        config = Config(
            width="100%",
            height=500,
            directed=True, 
            physics=True, # Bouncy physics
            hierarchical=False,
            nodeHighlightBehavior=True,
            highlightColor="#F7A7A6",
            collapsible=True
        )

        # Render the graph in Streamlit
        if len(nodes) > 1:
            return_value = agraph(nodes=nodes, edges=edges, config=config)
        else:
            st.warning("The agent could not find any relevant historical rules to map an impact for this event.")
        
    # --- 3. Text Breakdown & Sourcing Section ---
    st.subheader("Extracted Reasoning & Fact Checking")
    
    if sector_nodes:
        for sector in sector_nodes:
            impact_icon = "🟢" if "POSITIVE" in sector.get("impact", "").upper() else "🔴"
            st.markdown(f"{impact_icon} **{sector.get('id')}**: {sector.get('reasoning')}")
            st.caption(f"*(**Agent Cited Source:** `{sector.get('source_cited', 'Unknown')}`)*")
            st.markdown("---")
            
    st.write("### 📚 Raw Rules Retrieved from Database")
    if retrieved_sources:
        # retrieved_sources is now a list of metadata dictionaries!
        seen_files = set()
        for meta in retrieved_sources:
            filename = meta.get('filename', 'Unknown')
            # Use a set to avoid printing the exact same file 5 times if 5 chunks matched
            if filename not in seen_files:
                st.info(f"**Source:** `{filename}`\n\n**Logic Rule:** {meta.get('logic_rule', 'N/A')}\n\n**Metrics Used:** {meta.get('metrics_used', 'N/A')}")
                seen_files.add(filename)
    else:
        st.caption("No specific rules matched the filter criteria.")